title: The Life of Sushi Rais
baseURL: /
params:
  layout_style: grid
  palette: red
  header:
    title: Sushi Rais
    logo_img: ''
    has_nav: true
  footer:
    content: '&copyright 2020 Rais Rashdan - Made with ❤️ in Melbourne'
    links: []
    has_social: true
menu:
  main: []
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
