title: The Life of Sushi Rais
baseURL: /
params:
  layout_style: grid
  palette: blue
  header:
    title: Sushi Rais
    logo_img: ''
    has_nav: true
  footer:
    content: Made with ❤️ in Melbourne
    links: []
    has_social: true
menu:
  main: []
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
